//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klijent.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        WcfService.Korisnik Login(string ime, string lozinka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        System.Threading.Tasks.Task<WcfService.Korisnik> LoginAsync(string ime, string lozinka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/prikazGrupa", ReplyAction="http://tempuri.org/IUser/prikazGrupaResponse")]
        WcfService.Grupa[] prikazGrupa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/prikazGrupa", ReplyAction="http://tempuri.org/IUser/prikazGrupaResponse")]
        System.Threading.Tasks.Task<WcfService.Grupa[]> prikazGrupaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/zahtevZaPristupGrupi", ReplyAction="http://tempuri.org/IUser/zahtevZaPristupGrupiResponse")]
        void zahtevZaPristupGrupi(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/zahtevZaPristupGrupi", ReplyAction="http://tempuri.org/IUser/zahtevZaPristupGrupiResponse")]
        System.Threading.Tasks.Task zahtevZaPristupGrupiAsync(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/izlazakIzGrupe", ReplyAction="http://tempuri.org/IUser/izlazakIzGrupeResponse")]
        bool izlazakIzGrupe(WcfService.Korisnik korisnik, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/izlazakIzGrupe", ReplyAction="http://tempuri.org/IUser/izlazakIzGrupeResponse")]
        System.Threading.Tasks.Task<bool> izlazakIzGrupeAsync(WcfService.Korisnik korisnik, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/slanjePoruka", ReplyAction="http://tempuri.org/IUser/slanjePorukaResponse")]
        void slanjePoruka(WcfService.Poruke poruke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/slanjePoruka", ReplyAction="http://tempuri.org/IUser/slanjePorukaResponse")]
        System.Threading.Tasks.Task slanjePorukaAsync(WcfService.Poruke poruke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/citanjePoruka", ReplyAction="http://tempuri.org/IUser/citanjePorukaResponse")]
        WcfService.Poruke citanjePoruka(WcfService.Korisnik korisnik, int idKorisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/citanjePoruka", ReplyAction="http://tempuri.org/IUser/citanjePorukaResponse")]
        System.Threading.Tasks.Task<WcfService.Poruke> citanjePorukaAsync(WcfService.Korisnik korisnik, int idKorisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/onlineKorisnici", ReplyAction="http://tempuri.org/IUser/onlineKorisniciResponse")]
        WcfService.Korisnik[] onlineKorisnici(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/onlineKorisnici", ReplyAction="http://tempuri.org/IUser/onlineKorisniciResponse")]
        System.Threading.Tasks.Task<WcfService.Korisnik[]> onlineKorisniciAsync(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/vecUgrupi", ReplyAction="http://tempuri.org/IUser/vecUgrupiResponse")]
        bool vecUgrupi(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/vecUgrupi", ReplyAction="http://tempuri.org/IUser/vecUgrupiResponse")]
        System.Threading.Tasks.Task<bool> vecUgrupiAsync(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/IzmeniKorisnika", ReplyAction="http://tempuri.org/IAdmin/IzmeniKorisnikaResponse")]
        void IzmeniKorisnika(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/IzmeniKorisnika", ReplyAction="http://tempuri.org/IAdmin/IzmeniKorisnikaResponse")]
        System.Threading.Tasks.Task IzmeniKorisnikaAsync(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/DodajKorisnika", ReplyAction="http://tempuri.org/IAdmin/DodajKorisnikaResponse")]
        void DodajKorisnika(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/DodajKorisnika", ReplyAction="http://tempuri.org/IAdmin/DodajKorisnikaResponse")]
        System.Threading.Tasks.Task DodajKorisnikaAsync(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/OdobriUlazakUGrupu", ReplyAction="http://tempuri.org/IAdmin/OdobriUlazakUGrupuResponse")]
        void OdobriUlazakUGrupu(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/OdobriUlazakUGrupu", ReplyAction="http://tempuri.org/IAdmin/OdobriUlazakUGrupuResponse")]
        System.Threading.Tasks.Task OdobriUlazakUGrupuAsync(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/PonistiUlazakUGrupu", ReplyAction="http://tempuri.org/IAdmin/PonistiUlazakUGrupuResponse")]
        void PonistiUlazakUGrupu(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/PonistiUlazakUGrupu", ReplyAction="http://tempuri.org/IAdmin/PonistiUlazakUGrupuResponse")]
        System.Threading.Tasks.Task PonistiUlazakUGrupuAsync(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/prikazZahteva", ReplyAction="http://tempuri.org/IAdmin/prikazZahtevaResponse")]
        WcfService.GrupaKorisnici[] prikazZahteva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/prikazZahteva", ReplyAction="http://tempuri.org/IAdmin/prikazZahtevaResponse")]
        System.Threading.Tasks.Task<WcfService.GrupaKorisnici[]> prikazZahtevaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/prikaziSveKorisnike", ReplyAction="http://tempuri.org/IAdmin/prikaziSveKorisnikeResponse")]
        WcfService.Korisnik[] prikaziSveKorisnike();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdmin/prikaziSveKorisnike", ReplyAction="http://tempuri.org/IAdmin/prikaziSveKorisnikeResponse")]
        System.Threading.Tasks.Task<WcfService.Korisnik[]> prikaziSveKorisnikeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : Klijent.ServiceReference1.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<Klijent.ServiceReference1.IAdmin>, Klijent.ServiceReference1.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService.Korisnik Login(string ime, string lozinka) {
            return base.Channel.Login(ime, lozinka);
        }
        
        public System.Threading.Tasks.Task<WcfService.Korisnik> LoginAsync(string ime, string lozinka) {
            return base.Channel.LoginAsync(ime, lozinka);
        }
        
        public WcfService.Grupa[] prikazGrupa() {
            return base.Channel.prikazGrupa();
        }
        
        public System.Threading.Tasks.Task<WcfService.Grupa[]> prikazGrupaAsync() {
            return base.Channel.prikazGrupaAsync();
        }
        
        public void zahtevZaPristupGrupi(WcfService.GrupaKorisnici grupaKorisnici) {
            base.Channel.zahtevZaPristupGrupi(grupaKorisnici);
        }
        
        public System.Threading.Tasks.Task zahtevZaPristupGrupiAsync(WcfService.GrupaKorisnici grupaKorisnici) {
            return base.Channel.zahtevZaPristupGrupiAsync(grupaKorisnici);
        }
        
        public bool izlazakIzGrupe(WcfService.Korisnik korisnik, int idGrupe) {
            return base.Channel.izlazakIzGrupe(korisnik, idGrupe);
        }
        
        public System.Threading.Tasks.Task<bool> izlazakIzGrupeAsync(WcfService.Korisnik korisnik, int idGrupe) {
            return base.Channel.izlazakIzGrupeAsync(korisnik, idGrupe);
        }
        
        public void slanjePoruka(WcfService.Poruke poruke) {
            base.Channel.slanjePoruka(poruke);
        }
        
        public System.Threading.Tasks.Task slanjePorukaAsync(WcfService.Poruke poruke) {
            return base.Channel.slanjePorukaAsync(poruke);
        }
        
        public WcfService.Poruke citanjePoruka(WcfService.Korisnik korisnik, int idKorisnika) {
            return base.Channel.citanjePoruka(korisnik, idKorisnika);
        }
        
        public System.Threading.Tasks.Task<WcfService.Poruke> citanjePorukaAsync(WcfService.Korisnik korisnik, int idKorisnika) {
            return base.Channel.citanjePorukaAsync(korisnik, idKorisnika);
        }
        
        public WcfService.Korisnik[] onlineKorisnici(WcfService.Korisnik korisnik) {
            return base.Channel.onlineKorisnici(korisnik);
        }
        
        public System.Threading.Tasks.Task<WcfService.Korisnik[]> onlineKorisniciAsync(WcfService.Korisnik korisnik) {
            return base.Channel.onlineKorisniciAsync(korisnik);
        }
        
        public bool vecUgrupi(WcfService.Korisnik korisnik) {
            return base.Channel.vecUgrupi(korisnik);
        }
        
        public System.Threading.Tasks.Task<bool> vecUgrupiAsync(WcfService.Korisnik korisnik) {
            return base.Channel.vecUgrupiAsync(korisnik);
        }
        
        public void IzmeniKorisnika(WcfService.Korisnik korisnik) {
            base.Channel.IzmeniKorisnika(korisnik);
        }
        
        public System.Threading.Tasks.Task IzmeniKorisnikaAsync(WcfService.Korisnik korisnik) {
            return base.Channel.IzmeniKorisnikaAsync(korisnik);
        }
        
        public void DodajKorisnika(WcfService.Korisnik korisnik) {
            base.Channel.DodajKorisnika(korisnik);
        }
        
        public System.Threading.Tasks.Task DodajKorisnikaAsync(WcfService.Korisnik korisnik) {
            return base.Channel.DodajKorisnikaAsync(korisnik);
        }
        
        public void OdobriUlazakUGrupu(WcfService.GrupaKorisnici grupaKorisnici) {
            base.Channel.OdobriUlazakUGrupu(grupaKorisnici);
        }
        
        public System.Threading.Tasks.Task OdobriUlazakUGrupuAsync(WcfService.GrupaKorisnici grupaKorisnici) {
            return base.Channel.OdobriUlazakUGrupuAsync(grupaKorisnici);
        }
        
        public void PonistiUlazakUGrupu(WcfService.GrupaKorisnici grupaKorisnici) {
            base.Channel.PonistiUlazakUGrupu(grupaKorisnici);
        }
        
        public System.Threading.Tasks.Task PonistiUlazakUGrupuAsync(WcfService.GrupaKorisnici grupaKorisnici) {
            return base.Channel.PonistiUlazakUGrupuAsync(grupaKorisnici);
        }
        
        public WcfService.GrupaKorisnici[] prikazZahteva() {
            return base.Channel.prikazZahteva();
        }
        
        public System.Threading.Tasks.Task<WcfService.GrupaKorisnici[]> prikazZahtevaAsync() {
            return base.Channel.prikazZahtevaAsync();
        }
        
        public WcfService.Korisnik[] prikaziSveKorisnike() {
            return base.Channel.prikaziSveKorisnike();
        }
        
        public System.Threading.Tasks.Task<WcfService.Korisnik[]> prikaziSveKorisnikeAsync() {
            return base.Channel.prikaziSveKorisnikeAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        WcfService.Korisnik Login(string ime, string lozinka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Login", ReplyAction="http://tempuri.org/IUser/LoginResponse")]
        System.Threading.Tasks.Task<WcfService.Korisnik> LoginAsync(string ime, string lozinka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/prikazGrupa", ReplyAction="http://tempuri.org/IUser/prikazGrupaResponse")]
        WcfService.Grupa[] prikazGrupa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/prikazGrupa", ReplyAction="http://tempuri.org/IUser/prikazGrupaResponse")]
        System.Threading.Tasks.Task<WcfService.Grupa[]> prikazGrupaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/zahtevZaPristupGrupi", ReplyAction="http://tempuri.org/IUser/zahtevZaPristupGrupiResponse")]
        void zahtevZaPristupGrupi(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/zahtevZaPristupGrupi", ReplyAction="http://tempuri.org/IUser/zahtevZaPristupGrupiResponse")]
        System.Threading.Tasks.Task zahtevZaPristupGrupiAsync(WcfService.GrupaKorisnici grupaKorisnici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/izlazakIzGrupe", ReplyAction="http://tempuri.org/IUser/izlazakIzGrupeResponse")]
        bool izlazakIzGrupe(WcfService.Korisnik korisnik, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/izlazakIzGrupe", ReplyAction="http://tempuri.org/IUser/izlazakIzGrupeResponse")]
        System.Threading.Tasks.Task<bool> izlazakIzGrupeAsync(WcfService.Korisnik korisnik, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/slanjePoruka", ReplyAction="http://tempuri.org/IUser/slanjePorukaResponse")]
        void slanjePoruka(WcfService.Poruke poruke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/slanjePoruka", ReplyAction="http://tempuri.org/IUser/slanjePorukaResponse")]
        System.Threading.Tasks.Task slanjePorukaAsync(WcfService.Poruke poruke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/citanjePoruka", ReplyAction="http://tempuri.org/IUser/citanjePorukaResponse")]
        WcfService.Poruke citanjePoruka(WcfService.Korisnik korisnik, int idKorisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/citanjePoruka", ReplyAction="http://tempuri.org/IUser/citanjePorukaResponse")]
        System.Threading.Tasks.Task<WcfService.Poruke> citanjePorukaAsync(WcfService.Korisnik korisnik, int idKorisnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/onlineKorisnici", ReplyAction="http://tempuri.org/IUser/onlineKorisniciResponse")]
        WcfService.Korisnik[] onlineKorisnici(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/onlineKorisnici", ReplyAction="http://tempuri.org/IUser/onlineKorisniciResponse")]
        System.Threading.Tasks.Task<WcfService.Korisnik[]> onlineKorisniciAsync(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/vecUgrupi", ReplyAction="http://tempuri.org/IUser/vecUgrupiResponse")]
        bool vecUgrupi(WcfService.Korisnik korisnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/vecUgrupi", ReplyAction="http://tempuri.org/IUser/vecUgrupiResponse")]
        System.Threading.Tasks.Task<bool> vecUgrupiAsync(WcfService.Korisnik korisnik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : Klijent.ServiceReference1.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<Klijent.ServiceReference1.IUser>, Klijent.ServiceReference1.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService.Korisnik Login(string ime, string lozinka) {
            return base.Channel.Login(ime, lozinka);
        }
        
        public System.Threading.Tasks.Task<WcfService.Korisnik> LoginAsync(string ime, string lozinka) {
            return base.Channel.LoginAsync(ime, lozinka);
        }
        
        public WcfService.Grupa[] prikazGrupa() {
            return base.Channel.prikazGrupa();
        }
        
        public System.Threading.Tasks.Task<WcfService.Grupa[]> prikazGrupaAsync() {
            return base.Channel.prikazGrupaAsync();
        }
        
        public void zahtevZaPristupGrupi(WcfService.GrupaKorisnici grupaKorisnici) {
            base.Channel.zahtevZaPristupGrupi(grupaKorisnici);
        }
        
        public System.Threading.Tasks.Task zahtevZaPristupGrupiAsync(WcfService.GrupaKorisnici grupaKorisnici) {
            return base.Channel.zahtevZaPristupGrupiAsync(grupaKorisnici);
        }
        
        public bool izlazakIzGrupe(WcfService.Korisnik korisnik, int idGrupe) {
            return base.Channel.izlazakIzGrupe(korisnik, idGrupe);
        }
        
        public System.Threading.Tasks.Task<bool> izlazakIzGrupeAsync(WcfService.Korisnik korisnik, int idGrupe) {
            return base.Channel.izlazakIzGrupeAsync(korisnik, idGrupe);
        }
        
        public void slanjePoruka(WcfService.Poruke poruke) {
            base.Channel.slanjePoruka(poruke);
        }
        
        public System.Threading.Tasks.Task slanjePorukaAsync(WcfService.Poruke poruke) {
            return base.Channel.slanjePorukaAsync(poruke);
        }
        
        public WcfService.Poruke citanjePoruka(WcfService.Korisnik korisnik, int idKorisnika) {
            return base.Channel.citanjePoruka(korisnik, idKorisnika);
        }
        
        public System.Threading.Tasks.Task<WcfService.Poruke> citanjePorukaAsync(WcfService.Korisnik korisnik, int idKorisnika) {
            return base.Channel.citanjePorukaAsync(korisnik, idKorisnika);
        }
        
        public WcfService.Korisnik[] onlineKorisnici(WcfService.Korisnik korisnik) {
            return base.Channel.onlineKorisnici(korisnik);
        }
        
        public System.Threading.Tasks.Task<WcfService.Korisnik[]> onlineKorisniciAsync(WcfService.Korisnik korisnik) {
            return base.Channel.onlineKorisniciAsync(korisnik);
        }
        
        public bool vecUgrupi(WcfService.Korisnik korisnik) {
            return base.Channel.vecUgrupi(korisnik);
        }
        
        public System.Threading.Tasks.Task<bool> vecUgrupiAsync(WcfService.Korisnik korisnik) {
            return base.Channel.vecUgrupiAsync(korisnik);
        }
    }
}
